-- inserare roluri
INSERT INTO ROLES(role) VALUES ('ADMIN');
INSERT INTO ROLES(role) VALUES ('SUPPORT');
INSERT INTO ROLES(role) VALUES ('USER');

-- inserare useri initiali
INSERT INTO USERS(role_id, email, firstName, lastName, phone_number, password, token, is_verified) VALUES (1, 'admin@admin.com', 'Irina', 'Dumitru', '0711111111', '$2y$12$BdSnjuGzptHjUL3/RzR1kOuKMbaU8sPP.tHoGzCVBYT96BTL6XAOu', 'bla', true);
INSERT INTO USERS(role_id, email, firstName, lastName, phone_number, password, token, is_verified) VALUES (2, 'support@support.com', 'Irina', 'Dumitru', '0711111112', '$2y$12$Pf5R21UAdiLz20gDekFeMuKCho59ffHNh9gPSqzzxgkl.AZTGRLYu', 'blabla', true);

-- inserare categorii produse
INSERT INTO CATEGORIES(name_ro, name_en) VALUES ('Blugi', 'Jeans');
INSERT INTO CATEGORIES(name_ro, name_en) VALUES ('Bluze & Cămăși', 'Blouses');
INSERT INTO CATEGORIES(name_ro, name_en) VALUES ('Fuste', 'Skirts');
INSERT INTO CATEGORIES(name_ro, name_en) VALUES ('Hanorace', 'Hoodies');
INSERT INTO CATEGORIES(name_ro, name_en) VALUES ('Jachete & Paltoane', 'Jackets');
INSERT INTO CATEGORIES(name_ro, name_en) VALUES ('Pantaloni', 'Trousers');
INSERT INTO CATEGORIES(name_ro, name_en) VALUES ('Rochii', 'Dresses');
INSERT INTO CATEGORIES(name_ro, name_en) VALUES ('Tricouri', 'T-shirts');

-- trigger pentru a insera si in tabela STOCK stocurile produselor inserate in PRODUCTS
CREATE OR REPLACE FUNCTION insert_new_product_id()
    RETURNS TRIGGER
    LANGUAGE PLPGSQL
AS
$$
BEGIN
    INSERT INTO STOCK(product_id) VALUES (NEW.product_id);

    RETURN NEW;
END;
$$;

CREATE TRIGGER insert_new_product_id
    AFTER INSERT
    ON PRODUCTS
    FOR EACH ROW
EXECUTE PROCEDURE insert_new_product_id();

-- inserare produse

-- blugi
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (1, 'Blugi crop cu croiala ampla', 'Tommy Jeans', E'Caracteristici\nCuloare: alb\nImprimeu: uni\nCroiala: croiala ampla\nMaterial: denim\nStil: casual\nTalie: talie medie\nLungime: crop\n\nCompozitie\nExterior: 100% bumbac', 'https://fdcdn.akamaized.net/m/780x1132/products/34274/34273091/images/res_022b2d21454ab8b2575887020b161961.jpg?s=r4sRl-7jcyY-', 599.00);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (1, 'Blugi skinny cu talie inalta', 'EDC by Esprit', E'Caracteristici\nCuloare: albastru\nImprimeu: uni\nCroiala: skinny\nMaterial: denim\nStil: casual\nTalie: talie inalta\nLungime: lungi\nBuzunare: 5\nSistem inchidere: nasture, fermoar\nDetalii: aspect decolorat\n\nCompozitie\nExterior: 61% bumbac organic, 32% viscoza ( lenzing™ ecovero™), 5% elastomultiester (lycra®t400®), 2% elastan', 'https://fdcdn.akamaized.net/m/780x1132/products/31087/31086574/images/res_10da2eb86db84239def6eef0cd48815a.jpg?s=WOAVBz4lPwf5', 299.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (1, 'Blugi skinny', 'EDC by Esprit', E'Caracteristici\nCuloare: negru\nImprimeu: uni\nCroiala: skinny\nMaterial: denim\nStil: casual\nTalie: talie inalta\nLungime: lungi\nBuzunare: 5\nSistem inchidere: nasture, fermoar\n\nCompozitie\nExterior: 53% bumbac, 39% viscoza, 6% elastomultiester, 2% elastan', 'https://fdcdn.akamaized.net/m/780x1132/products/31087/31086598/images/res_9f742d2a084873d4f0759076b1583235.jpg?s=8DktKMMl59Wr', 299.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (1, 'Blugi cu croiala ampla si 5 buzunare', 'CALVIN KLEIN', E'Caracteristici\nCuloare: gri inchis\nImprimeu: uni\nCroiala: croiala ampla\nMaterial: denim\nStil: casual\nTalie: talie inalta\nLungime: lungi\nBuzunare: 5\nSistem inchidere: nasture\n\nCompozitie\nExterior: 98% bumbac organic, 2% elastan', 'https://fdcdn.akamaized.net/m/780x1132/products/34275/34274715/images/res_55f4951be45d1eca2c81c53b398377ab.jpg?s=NKjHrkxPvh9u', 649.00);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (1, 'EDC by Blugi skinny cu aspect peliculizat', 'Esprit', E'Caracteristici\nCuloare: negru\nImprimeu: uni\nCroiala: skinny\nMaterial: sintetic\nStil: casual\nTalie: talie medie\nLungime: lungi\nBuzunare: 5\nSistem inchidere: nasture, fermoar\nDetalii: aspect peliculizat, bucle pentru curea\n\nCompozitie\nExterior: 86% bumbac, 13% poliester, 1% elastan', 'https://fdcdn.akamaized.net/m/780x1132/products/31086/31085662/images/res_1cdf8034043a45dc79c13fda09ef10ec.jpg?s=08_Fjyg0oVx9', 299.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (1, 'Blugi crop cu croiala ampla', 'Tommy Jeans', E'Caracteristici\nCuloare: gri antracit\nImprimeu: uni\nCroiala: croiala ampla\nMaterial: denim\nStil: casual\nTalie: talie inalta\nLungime: crop\nBuzunare: pe ambele parti\nSistem inchidere: nasture, fermoar\n\nCompozitie\nExterior: 62% lyocell, 38% bumbac', 'https://fdcdn.akamaized.net/m/780x1132/products/34273/34272995/images/res_638a8e97ab2fad00695c2755f0b36c5b.jpg?s=2pUQSy_J7dOA', 449.00);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (1, 'Blugi bootcut din amestec de lyocell si bumbac organic', 'Tommy Hilfiger', E'Caracteristici\nCuloare: bleumarin inchis\nImprimeu: uni\nCroiala: bootcut\nMaterial: denim\nStil: casual\nTalie: talie inalta\nLungime: lungi\nBuzunare: 5\nSistem inchidere: nasture, fermoar\n\nCompozitie\nExterior: 56% lyocell, 37% bumbac organic, 5% poliester, 2% elastan', 'https://fdcdn.akamaized.net/m/780x1132/products/34276/34275923/images/res_838e016a84f9bf85de817d93e78a8c3e.jpg?s=w2UCRj_z8Jj8', 649.00);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (1, 'Blugi mom fit cu talie inalta', 'DeFacto', E'Caracteristici\nCuloare: albastru deschis\nImprimeu: uni\nCroiala: mom fit\nMaterial: denim\nStil: casual\nTalie: talie inalta\nLungime: lungi\nBuzunare: 5\nSistem inchidere: nasture, fermoar\n\nCompozitie\nExterior: 100% bumbac', 'https://fdcdn.akamaized.net/m/780x1132/products/34448/34447790/images/res_4868053313d9fcd5cf5e5217cc0a4847.jpg?s=V8BeWoleUOsZ', 79.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (1, 'Blugi mom fit cu cusaturi contrastante', 'Missguided', E'Caracteristici\nCuloare: negru\nImprimeu: uni\nCroiala: mom fit\nMaterial: denim\nStil: casual\nTalie: talie inalta\nLungime: lungi\nDetalii: bucle pentru curea, cusaturi contrastante\n\nCompozitie\nExterior: 95% poliester, 5% elastan', 'https://fdcdn.akamaized.net/m/780x1132/products/33990/33989211/images/res_a48454fff0c8401d9acfdec2c1dc36e3.jpg?s=DDF2OwIWYx1U', 209.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (1, 'Blugi cu terminatie nefinisata', 'American Eagle', E'Caracteristici\nCuloare: gri antracit\nImprimeu: uni\nCroiala: slim fit\nMaterial: denim\nStil: casual\nTalie: talie inalta\nLungime: crop\nBuzunare: 5\nSistem inchidere: nasture, fermoar\nDetalii: bucle pentru curea, terminatie nefinisata\n\nCompozitie\nExterior: 47% bumbac, 30% viscoza, 21% poliester, 2% elastan', 'https://fdcdn.akamaized.net/m/780x1132/products/34151/34150257/images/res_89fd7e19f47b257a4a8aee2b4fd0f356.jpg?s=7x9uCZwdqkxL', 329.99);

-- bluze & camasi
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (2, 'Bluza cu funda', 'Oltre', E'Caracteristici\nCuloare: negru\nImprimeu: uni\nStil: casual\nCroiala: regular fit\nMaterial: poliester, bumbac\nDecolteu: rotund\nLungime maneca: maneca trei sferturi\nDetalii: funda\n\nCompozitie\nExterior: 56% poliester, 44% bumbac', 'https://fdcdn.akamaized.net/m/780x1132/products/33596/33595923/images/res_cc3704c3857248f88b3e0dffbabae957.jpg?s=j1ZfM2tt5NDa', 389.00);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (2, 'Bluza evazata cu pliuri', 'Trendyol', E'Caracteristici\nCuloare: oranj stins\nStil: casual\nCroiala: evazat\nMaterial: poliester\nGuler: scurt cu snur\nLungime maneca: maneca lunga\nDetalii: cu pliuri\n\nCompozitie\nExterior: 100% poliester', 'https://fdcdn.akamaized.net/m/780x1132/products/34443/34442490/images/res_6e1d947b6bf0541a33fbaa3f39c794a2.jpg?s=Hqyb9bsyvF1C', 149.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (2, 'Bluza cu decolteu in V si fenta cu capse', 'NA-KD', E'Caracteristici\nCuloare: bej\nImprimeu: uni\nStil: casual\nCroiala: regular fit\nMaterial: bumbac\nDecolteu: in v\nLungime maneca: maneca lunga\nDetalii: fenta cu capse\nLinie Brand: na-kd x sara sieppi\n\nCompozitie\nExterior: 100% bumbac', 'https://fdcdn.akamaized.net/m/780x1132/products/34390/34389783/images/res_cac9b785a99fcc30097913b09fbb0e83.jpg?s=oSK5lzEaAOgu', 159.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (2, 'Bluza lejera cu terminatie asimetrica', 'Zabaione', E'Caracteristici\nCuloare: alb\nImprimeu: uni\nStil: casual\nCroiala: lejer\nMaterial: viscoza\nDecolteu: rotund\nLungime maneca: maneca lunga\nDetalii: dantela crosetata, material vaporos\n\nCompozitie\nExterior: 100% viscoza', 'https://fdcdn.akamaized.net/m/780x1132/products/34310/34309397/images/res_7575b4abc1c909db1c50ce1f3888961a.jpg?s=5HivSBt6erVG', 169.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (2, 'Bluza din amestec de modal cu bretele incrucisate Josy', 'Z ONE by ZABAIONE', E'Caracteristici\nCuloare: bleumarin\nImprimeu: uni\nStil: casual\nCroiala: regular fit\nMaterial: bumbac, modal\nDecolteu: in v, cu benzi incrucisate\nLungime maneca: maneca trei sferturi\n\nCompozitie\nExterior: 46% bumbac, 46% modal, 8% elastan', 'https://fdcdn.akamaized.net/m/780x1132/products/34018/34017449/images/res_a47968c4c2d51887ae81b5a1ae7fdf69.jpg?s=uy7X9E1H5jR4', 89.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (2, 'Camasa stil victorian cu detalii brodate de dantela', 'Trendyol', E'Caracteristici\nCuloare: oranj persan\nImprimeu: uni\nStil: casual\nMaterial: bumbac\nCroiala: regular fit\nGuler: scurt\nTip maneca: bufante\nLungime maneca: maneca lunga\nDetalii: din dantela brodata\nSistem inchidere: nasturi\n\nCompozitie\nExterior: 100% bumbac', 'https://fdcdn.akamaized.net/m/780x1132/products/34443/34442452/images/res_3775ad2e228e720d06b7f0b845e5b93c.jpg?s=IudWwdQCyjas', 119.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (2, 'Camasa supradimensionata de denim cu model colorblock', 'Missguided', E'Caracteristici\nCuloare: bej\nImprimeu: uni\nStil: casual\nMaterial: denim\nCroiala: supradimensionat\nGuler: clasic\nTip maneca: ample\nLungime maneca: maneca lunga\nBuzunare: 2 pe piept, cu clapa si nasturi\nDetalii: design colorblock\nSistem inchidere: nasturi\n\nCompozitie\nExterior: 100% bumbac', 'https://fdcdn.akamaized.net/m/780x1132/products/33990/33989198/images/res_e52d22fe687cc1fb9ca9a38112adf790.jpg?s=WLAyv2o0DFjd', 239.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (2, 'Camasa lejera cu buzunare pe piept', 'DeFacto', E'Caracteristici\nCuloare: crem/bleumarin/oranj\nImprimeu: carouri\nStil: casual\nMaterial: poliester, bumbac\nCroiala: supradimensionat\nGuler: ascutit\nLungime maneca: maneca lunga\nBuzunare: 2 pe piept\nSistem inchidere: nasturi\n\nCompozitie\nExterior: 45% bumbac, 25% poliester, 15% acrilic, 15% alte fibre', 'https://fdcdn.akamaized.net/m/780x1132/products/34362/34361967/images/res_88c5ffc4f0603c6101c523bc1a8724ce.jpg?s=3FJm_S8kvHox', 79.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (2, 'Camasa de reiat cu buzunare aplicate', 'DeFacto', E'Caracteristici\nCuloare: maro\nImprimeu: uni\nStil: casual\nMaterial: bumbac\nCroiala: supradimensionat\nGuler: ascutit\nTip maneca: ampla\nLungime maneca: maneca lunga\nBuzunare: 2 aplicate\nSistem inchidere: nasturi\n\nCompozitie\nExterior: 100% bumbac', 'https://fdcdn.akamaized.net/m/780x1132/products/34223/34222389/images/res_be600dc7f549702337f093c0ca728f57.jpg?s=46w5ozyRDWRo', 129.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (2, 'Camasa cu imprimeu floral si buzunar pe piept Mushuro', 'Mango', E'Caracteristici\nCuloare: rosu/albastru/verde\nImprimeu: floral\nStil: casual\nMaterial: poliester\nCroiala: regular fit\nGuler: cu revere decupate\nLungime maneca: maneca lunga\nBuzunare: unul pe piept\nDetalii: material vaporos\nSistem inchidere: nasturi\n\nCompozitie\nExterior: 100% poliester', 'https://fdcdn.akamaized.net/m/780x1132/products/34237/34236152/images/res_15d4ec149672b5660b7d07511eac3a00.jpg?s=ZsOHslkhv1Wj', 169.99);

-- fuste
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (3, 'Fusta maxi cu model cu buline Domi', 'Mango', E'Caracteristici\nCuloare: negru\nStil: casual\nImprimeu: buline\nCroiala: evazat\nMaterial: poliester\nTalie: inalta\nLungime: lunga\nDetalii: volane\n\nCompozitie\nExterior: 70% poliester, 30% poliester reciclat\nCaptuseala: poliester 100%', 'https://fdcdn.akamaized.net/m/780x1132/products/33921/33920461/images/res_24b98ea1a4104ab1bb12c83506355c72.jpg?s=kOe2uHneAOmJ', 199.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (3, 'Fusta mini din amestec de bumbac organic', 'Tommy Jeans', E'Caracteristici\nCuloare: bleumarin/alb/rosu\nStil: casual\nImprimeu: dungi\nCroiala: creion\nMaterial: bumbac organic\nTalie: medie\nLungime: mini\nDetalii: slit lateral\n\nCompozitie\nExterior: 74% bumbac organic, 24% poliamida, 2% elastan', 'https://fdcdn.akamaized.net/m/780x1132/products/34274/34273126/images/res_6c3993315bd0f8a64e373de7e260aa61.jpg?s=c0ioKvnd7FFa', 449.00);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (3, 'Fusta de denim peliculizat cu croiala in A si cusaturi contrastante', 'Missguided', E'Caracteristici\nCuloare: negru\nStil: casual\nImprimeu: uni\nCroiala: in a\nMaterial: bumbac, denim\nTalie: medie\nLungime: mini\nDetalii: cusaturi contrastante, aspect peliculizat\n\nCompozitie\nExterior: 100% bumbac', 'https://fdcdn.akamaized.net/m/780x1132/products/33990/33989203/images/res_c05ad483d3baed4593e11ce67070ef45.jpg?s=CmeVhyWXS9Vl', 189.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (3, 'Fusta midi cu pliuri si animal print', 'Esprit', E'Caracteristici\nCuloare: negru/maro\nStil: casual\nImprimeu: animal print\nCroiala: evazat\nMaterial: poliester\nTalie: inalta\nLungime: midi\nDetalii: cu pliuri\n\nCompozitie\nExterior: 95% poliester, 5% elastan', 'https://fdcdn.akamaized.net/m/780x1132/products/34310/34309166/images/res_15bc4855b6632889a857abe90ec41898.jpg?s=rG6WROxbsgeI', 299.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (3, 'Fusta mini cu terminatie cu pliuri', 'DeFacto', E'Caracteristici\nCuloare: maro\nStil: casual\nImprimeu: uni\nCroiala: in a\nMaterial: piele ecologica\nTalie: inalta\nLungime: mini\n\nCompozitie\nExterior: 100% poliester cu pelicula de poliuretan', 'https://fdcdn.akamaized.net/m/780x1132/products/34225/34224278/images/res_c0be2ce4cefff96b9cb4df54903c2b64.jpg?s=HMhUV2BtgNTB', 89.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (3, 'Fusta midi cu aspect lacuit Boli', 'Mango', E'Caracteristici\nCuloare: violet pruna\nStil: casual\nImprimeu: uni\nCroiala: creion\nMaterial: piele ecologica\nTalie: medie\nLungime: midi\n\nCompozitie\nExterior: 100% viscoza cu pelicula de poliuretan\nCaptuseala: captuseala buzunar: 100% poliester', 'https://fdcdn.akamaized.net/m/780x1132/products/34236/34235768/images/res_b8d7883c439dce6f7a87f9d1d98e4449.jpg?s=Y-3acOvTMnYJ', 199.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (3, 'Fusta mini cu terminatie cu volane', 'Trendyol', E'Caracteristici\nCuloare: negru/albastru/alb\nStil: casual\nImprimeu: carouri\nCroiala: dreapta\nMaterial: poliester, bumbac, acril\nTalie: medie\nLungime: mini\nDetalii: terminatie cu volan\n\nCompozitie\nExterior: 40% poliester, 40% bumbac, 20% acrilic', 'https://fdcdn.akamaized.net/m/780x1132/products/34289/34288552/images/res_6d30069d1ae10fbf2629bc02b0594528.jpg?s=OVTcHPnUlQsC', 99.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (3, 'Fusta cu talie inalta si model petrecut', 'NA-KD', E'Caracteristici\nCuloare: verde sparanghel\nStil: casual\nImprimeu: uni\nCroiala: evazat\nMaterial: sintetic\nTalie: inalta\nLungime: mini\nDetalii: design petrecut\nSistem inchidere: fermoar\n\nCompozitie\nExterior: 75% poliester, 17% viscoza, 8% elastan', 'https://fdcdn.akamaized.net/m/780x1132/products/34446/34445466/images/res_abf99958616fb3c801e96787ea987521.jpg?s=FSXQo28p246I', 229.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (3, 'Fusta mini in carouri', 'Trendyol', E'Caracteristici\nCuloare: camel/oranj stins/alb prafuit\nStil: casual\nImprimeu: carouri\nCroiala: dreapta\nMaterial: bumbac\nTalie: inalta\nLungime: mini\nSistem inchidere: fermoar\n\nCompozitie\nExterior: 50% bumbac, 50% poliester', 'https://fdcdn.akamaized.net/m/780x1132/products/34227/34226851/images/res_ceb76778c56a93894f22d7a1b32bc706.jpg?s=stuQWI1vKxiD', 129.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (3, 'Fusta cu talie inalta si aspect plisat', 'KOTON', E'Caracteristici\nCuloare: roz prafuit\nStil: casual\nImprimeu: uni\nCroiala: evazat\nMaterial: poliester, elastan\nTalie: inalta\nLungime: medie\nDetalii: aspect plisat\n\nCompozitie\nExterior: 96^ poliester, 4% elastan', 'https://fdcdn.akamaized.net/m/780x1132/products/34278/34277162/images/res_ee7926b943ad6dc529afc664b3757bca.jpg?s=2jcSYNFhelZH', 139.99);

-- hanorace
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (4, 'Hanorac cu model logo dryCELL Modern Sports', 'Puma', E'Caracteristici\nCuloare: alb/oranj/bleumarin\nImprimeu: logo\nStil: casual\nCroiala: lejer\nMaterial: bumbac\nLungime maneci: lungi\nDetalii: design crop\nTehnologie: drycell\nInchidere: fara inchidere\n\nCompozitie\nExterior: 67% bumbac, 26% poliester, 7% elastan', 'https://fdcdn.akamaized.net/m/780x1132/products/34174/34173822/images/res_0fe78a3f2db9f78f4e6113a42792fa85.jpg?s=WaVsnCQQX_rn', 259.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (4, 'Hanorac cu broderii florale Rosita', 'Z ONE by ZABAIONE', E'Caracteristici\nCuloare: roz somon\nImprimeu: floral\nStil: casual\nCroiala: regular fit\nMaterial: poliester, bumbac\nManeci: cu mansete\nLungime maneci: lungi\nDetalii: maneci brodate\nInchidere: fermoar\n\nCompozitie\nExterior: 80% poliester, 20% bumbac', 'https://fdcdn.akamaized.net/m/780x1132/products/34018/34017583/images/res_a68d1c510cd257916597dfdd740bf7a9.jpg?s=twpBMn1ldhcF', 179.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (4, 'Hanorac din bumbac cu buzunar kangaroo', 'Levi''s', E'Caracteristici\nCuloare: gri\nImprimeu: logo\nStil: casual\nCroiala: regular fit\nMaterial: bumbac\nManeci: cu mansete\nLungime maneci: lungi\nBuzunare: kangaroo\n\nCompozitie\nExterior: 100% bumbac', 'https://fdcdn.akamaized.net/m/780x1132/products/34502/34501983/images/res_0af4b0d2d61b2fa1befe2bd12efac51f.jpg?s=2h_KhaDEN0Qj', 349.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (4, 'Hanorac lejer cu maneci cazute', 'DeFacto', E'Caracteristici\nCuloare: verde menta\nImprimeu: uni\nStil: casual\nCroiala: lejer\nMaterial: poliester, bumbac\nManeci: cazute\nLungime maneci: lungi\nDetalii: gluga ajustabila cu snur\n\nCompozitie\nExterior: 55% poliester, 45% bumbac', 'https://fdcdn.akamaized.net/m/780x1132/products/34424/34423263/images/res_231cef086b475bac21ef1826b0cbf50a.jpg?s=0dSYt5zs96r6', 69.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (4, 'Hanorac cu buzunare si fenta cu fermoar Gymclass', 'Geographical Norway', E'Caracteristici\nCuloare: gri inchis/rosu/maro camel\nImprimeu: uni, logo\nStil: casual\nCroiala: regular fit\nMaterial: poliester\nLungime maneci: lungi\nDetalii: fenta cu fermoar\nInchidere: fara inchidere\n\nCompozitie\nExterior: 100% poliester', 'https://fdcdn.akamaized.net/m/780x1132/products/34092/34091914/images/res_aa9213a42d3f937d738735efa59a80aa.jpg?s=pG5-kJalqHjS', 389.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (4, 'Hanorac tricotat fin cu maneci cazute', 'DeFacto', E'Caracteristici\nCuloare: verde oliv\nImprimeu: uni\nStil: casual\nCroiala: regular fit\nMaterial: sintetic\nManeci: cazute\nLungime maneci: lungi\nDetalii: mansete si terminatie striate, gluga cu snur pentru ajustare\nInchidere: fara inchidere\n\nCompozitie\nExterior: 70% acrilic, 23% poliester, 7% elastan', 'https://fdcdn.akamaized.net/m/780x1132/products/34424/34423189/images/res_b424fd32f25246f247ae5fdcba1682d1.jpg?s=6NzihtfwqoTh', 69.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (4, 'Hanorac crop cu maneci cu model grafic', 'DeFacto', E'Caracteristici\nCuloare: negru/alb\nImprimeu: text, grafic\nStil: casual\nCroiala: regular fit\nMaterial: bumbac\nLungime maneci: lungi\nDetalii: talie elastica, design crop\nInchidere: fara inchidere\n\nCompozitie\nExterior: 50% bumbac, 50% poliester', 'https://fdcdn.akamaized.net/m/780x1132/products/34362/34361698/images/res_1b3afa488be1745e55eb6e51aa13cc35.jpg?s=F7ravLb-NA8h', 69.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (4, 'Hanorac crop cu logo', 'Puma', E'Caracteristici\nCuloare: negru/argintiu\nImprimeu: logo\nStil: casual\nCroiala: lejer\nMaterial: poliester, bumbac\nManeci: cazute, terminatii elastice\nLungime maneci: lungi\nDetalii: gluga cu snur pentru ajustare, aspect crop\nInchidere: fara inchidere\n\nCompozitie\nExterior: 68% bumbac, 32% poliester', 'https://fdcdn.akamaized.net/m/780x1132/products/33979/33978215/images/res_f30c8a5bc104a1fe025fda712f54868a.jpg?s=sOn5JNHQpuD1', 309.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (4, 'Hanorac cu imprimeu grafic si maneci cazute', 'Levi''s', E'Caracteristici\nCuloare: lila/gri inchis\nImprimeu: grafic\nStil: casual\nCroiala: lejer\nMaterial: bumbac\nManeci: cazute\nLungime maneci: lungi\nBuzunare: unul, kangaroo\nDetalii: gluga cu snur pentru ajustare, terminatii striate\nInchidere: fara inchidere\n\nCompozitie\nExterior: 100% bumbac', 'https://fdcdn.akamaized.net/m/780x1132/products/34259/34258987/images/res_adc75bc2eb60ad80a120b613049a2fef.jpg?s=WRnYdNZ54iUo', 399.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (4, 'Hanorac cu buzunar kangaroo si broderie Planet', 'VIOLETA BY MANGO', E'Caracteristici\nCuloare: bej\nImprimeu: text\nStil: casual\nCroiala: lejer\nMaterial: bumbac\nLungime maneci: lungi\nBuzunare: kangaroo\nInchidere: fara inchidere\n\nCompozitie\nExterior: 83% bumbac, 17% poliester\nCaptuseala: captuseala gluga: 100% bumbac\nMaterial garnituri: 96% bumbac, 4% elastan', 'https://fdcdn.akamaized.net/m/780x1132/products/34394/34393917/images/res_11f7cdb749f6bf32d4cf737d2ebd5a22.jpg?s=QOavXtAT7hPF', 169.99);

-- jachete & paltoane
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (5, 'Geaca cu vatelina si imprimeu floral', 'Geox', E'Caracteristici\nTip: geaca\nCuloare: negru\nImprimeu: floral\nMaterial: sintetic\nStil: casual\nCroiala: regular fit\nGuler: scurt\nGluga: cu gluga\nLungime maneci: lungi\nInchidere: fermoar\n\nCompozitie\nExterior: 100% poliester', 'https://fdcdn.akamaized.net/m/780x1132/products/33156/33155185/images/res_aff30f74f9723f14ce7827c43d158007.jpg?s=RVsS6Rlmpe_b', 1359.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (5, 'Geaca parka Wildwood', 'Jack Wolfskin', E'Caracteristici\nTip: geaca\nCuloare: albastru\nImprimeu: uni\nMaterial: poliamida, bumbac organic\nStil: casual\nCroiala: regular fit\nGuler: inalt\nGluga: cu gluga\nManeci: benzi cu capse\nLungime maneci: lungi\nBuzunare: 2 cu refilet si fermoar frontale, unul interior\nDetalii: material respirabil, impermeabile, nu contine pfc, snur in talie pentru ajustare, logo brodat discret, rezistenta la vant, izolatie termica, gluga ajustabila si detasabila\nInchidere: fermoar\nTehnologie: stormlock, texapore, microguard woolblend\n\nCompozitie\nExterior: 54% bumbac organic, 46% poliamida\nCaptuseala: 100% poliester\nUmplutura: 50% lana, 50% poliester', 'https://fdcdn.akamaized.net/m/780x1132/products/34207/34206930/images/res_450286cab605d401255133aefb348c19.jpg?s=VIw7kBA7m_ns', 1379.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (5, 'Geaca pentru snowboarding Cyrstaline Hybrid', 'O''Neill', E'Caracteristici generale\nTip produs: geaca\nSport: snowboarding\nCuloare: verde oliv\nImprimeu: uni\nStil: cu gluga\nCroiala: regular fit\nMaterial: poliester\nTehnologie material: hyperdry, o''neill firewall\nDetalii: impermeabile, cusaturi izolate\nSezon: toamna-iarna\nTip inchidere: fermoar\nNivel impermeabilitate: 10000 mm\nNivel respirabilitate (g/m²/24 h): 10000\nDetalii material\nExterior: 100% poliester\nCaptuseala: 100%poliester\nUmplutura: 100% poliester', 'https://fdcdn.akamaized.net/m/780x1132/products/34325/34324349/images/res_bdb1b8d1b9a9e055ccb53934a6ab4b38.jpg?s=iWY3cVtp0mAQ', 709.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (5, 'Geaca lunga matlasata', 'Oltre', E'Caracteristici\nTip: geaca\nCuloare: bej\nImprimeu: uni\nMaterial: sintetic\nStil: casual\nCroiala: regular fit\nGluga: cu gluga\nLungime maneci: lungi\nBuzunare: laterale\nDetalii: curea elastica\nInchidere: fermoar\n\nCompozitie\nExterior: 100% poliamida', 'https://fdcdn.akamaized.net/m/780x1132/products/33357/33356797/images/res_bd18cc48f2d1f9320942d0e161ebe7b7.jpg?s=nePBnMQzhQAz', 1169.00);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (5, 'Jacheta din tuid cu lanturi decorative Canela', 'Mango', E'Caracteristici\nTip: jacheta\nCuloare: negru\nImprimeu: uni\nMaterial: bumbac, poliester, lana\nStil: casual, office\nCroiala: regular fit\nGluga: fara gluga\nLungime maneci: lungi\nBuzunare: aplicatie frontala\nDetalii: material dinn tweed, nasturi decorativi, lanturi decorative\nInchidere: fara inchidere\n\nCompozitie\nExterior: 80% poliester, 13% lana, 7% bumbac\nCaptuseala: poliester 100%', 'https://fdcdn.akamaized.net/m/780x1132/products/33921/33920182/images/res_f9e04c9332b86e480f898a7554037433.jpg?s=4aJ1PzO001Je', 399.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (5, 'Palton din amestec de lana cu guler detasabil de blana sintetica Hilton', 'Mango', E'Caracteristici\nCuloare: taupe\nImprimeu: uni\nStil: casual\nMaterial: poliester, lana\nCroiala: regular fit\nGuler: cu blana sintetica detasabila\nLungime maneci: lungi\nSistem inchidere: snur\n\nCompozitie\nExterior: 59% poliester, 41% lana\nCaptuseala: 55% poliester, 45% viscoza\nDetalii material: guler de blana sintetica: 100% poliester', 'https://fdcdn.akamaized.net/m/780x1132/products/32924/32923060/images/res_256befe8be6bb1fd482faba32c2055c9.jpg?s=Wm2pJ48ycRoE', 699.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (5, 'Haina din blana sintetica cu aspect pufos Chilly', 'Mango', E'Caracteristici\nCuloare: galben inchis\nImprimeu: uni\nStil: casual\nMaterial: blana artificiala\nCroiala: regular fit\nGuler: sal\nLungime maneci: lungi\nBuzunare: in cusaturile laterale\nSistem inchidere: nasturi\n\nCompozitie\nExterior: 100% poliester\nCaptuseala: captuseala: 100% poliester', 'https://fdcdn.akamaized.net/m/780x1132/products/33921/33920103/images/res_15806ec272def737d787e0075fb6c1b8.jpg?s=FBwp0aUiWpFI', 549.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (5, 'Palton din material teddy', 'Missguided', E'Caracteristici\nCuloare: roz pastel\nImprimeu: uni\nStil: casual\nMaterial: poliester\nCroiala: regular fit\nGuler: cu revere decupate\nLungime maneci: 3/4\nBuzunare: 2 frontale\nDetalii: aspect pufos\nSistem inchidere: capse\n\nCompozitie\nExterior: 100% poliester', 'https://fdcdn.akamaized.net/m/780x1132/products/33990/33989376/images/res_ada9ebf23d0ff8eb6d7414a50d32e5c1.jpg?s=LKTtteYTGSX-', 489.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (5, 'Palton supradimensionat din amestec de lana Valeria', 'Zabaione', E'Caracteristici\nCuloare: maro\nImprimeu: uni\nStil: casual\nMaterial: poliester, lana\nCroiala: supradimensionat\nGuler: cu revere decupate\nLungime maneci: lungi\nBuzunare: 2 aplicate\nSistem inchidere: nasturi\n\nCompozitie\nExterior: 60% lana, 40% poliester', 'https://fdcdn.akamaized.net/m/780x1132/products/34310/34309566/images/res_11939d0dbe06f29605edd02649bc6408.jpg?s=oRWiMQIifupL', 399.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (5, 'Palton din amestec de lana cu cordon', 'DeFacto', E'Caracteristici\nCuloare: rosu inchis\nImprimeu: uni\nStil: casual, office\nMaterial: poliester, lana\nCroiala: regular fit\nGuler: cu revere\nLungime maneci: lungi\nSistem inchidere: snur\n\nCompozitie\nExterior: 55% poliester, 30% lana, 15% alte fibre\nCaptuseala: captuseala: 100% poliester', 'https://fdcdn.akamaized.net/m/780x1132/products/34448/34447191/images/res_66d659079105e649dab7b62285185c70.jpg?s=0sWMOCGN2lzf', 299.99);

-- pantaloni
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (6, 'Pantaloni culotte in carouri Bermu', 'Mango', E'Caracteristici\nCuloare: maro\nStil: casual\nMaterial: poliester, viscoza, elastan\nImprimeu: carouri\nCroiala: croiala ampla\nLungime: capri\nTalie: inalta\nBuzunare: 2 cu refilet pe partea din spate, 2 laterale\nSistem inchidere: fermoar, bucle metalice\n\nCompozitie\nExterior: 52% viscoza, 46% poliester, 2% elastan\nCaptuseala: 100% poliester\n', 'https://fdcdn.akamaized.net/m/780x1132/products/33618/33617619/images/res_295fcae5fb85eae5a26a59578dee5693.jpg?s=ybWrIgFOQ5du', 169.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (6, 'Pantaloni crop jogger cu pensa frontala', 'Oltre', E'Caracteristici\nCuloare: gri deschis\nStil: casual, office\nMaterial: poliester, viscoza\nImprimeu: uni\nCroiala: slim fit\nLungime: crop\nTalie: medie\nDetalii: pensa pe partea din fata, talie cu snur de ajustare\n\nCompozitie\nExterior: 88% poliester, 9% viscoza, 3% elastan\nCaptuseala: captuseala 1: 50% acetat, 50% viscoza, captuseala 2: 80% poliester, 20% bumbac\n', 'https://fdcdn.akamaized.net/m/390x566/products/33597/33596160/images/res_356c8d072d9535b39c7f09ab4b380ea8.jpg?s=L6PQWIeCRp4i', 389.00);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (6, 'Pantaloni cu talie inalta si fronseuri', 'NA-KD', E'Caracteristici\nCuloare: crem\nStil: casual, office\nMaterial: sintetic\nImprimeu: uni\nCroiala: slim fit\nLungime: lungi\nTalie: inalta\nDetalii: bucle pentru curea, fronseuri pe partea inferioara\n\nCompozitie\nExterior: 77% poliester, 21% viscoza, 2% elastan\n', 'https://fdcdn.akamaized.net/m/780x1132/products/34390/34389804/images/res_96b16d1844cab58df2c4becb33c346f1.jpg?s=SX09ncSr0QcD', 289.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (6, 'Pantaloni crop cu croiala ampla si model in carouri Clean', 'Mango', E'Caracteristici\nCuloare: gri\nStil: casual, office\nMaterial: poliester\nImprimeu: carouri\nCroiala: croiala ampla\nLungime: crop\nTalie: inalta\nBuzunare: in cusaturile laterale, cu refilet pe partea din spate\nSistem inchidere: fermoar si nasture\n\nCompozitie\nExterior: 100% poliester\nCaptuseala: captuseala: 100% poliester\nMaterial garnituri: 100% poliester\n', 'https://fdcdn.akamaized.net/m/780x1132/products/32108/32107452/images/res_f32d6272e4d2204ff20b7cf6e477d7ca.jpg?s=Zam7OiwkubxH', 169.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (6, 'Pantaloni cu pliuri frontale Sarah', 'Mango', E'Caracteristici\nCuloare: maro inchis melange/negru\nStil: office\nMaterial: poliester, viscoza\nImprimeu: carouri\nCroiala: regular fit\nLungime: crop\nTalie: elastica, medie\nDetalii: pliuri frontale\nSistem inchidere: fara inchidere\n\nCompozitie\nExterior: 66% poliester, 32% viscoza, 2% elastan\nCaptuseala: 100% poliester\n', 'https://fdcdn.akamaized.net/m/780x1132/products/33364/33363127/images/res_ffa6c5f98617197cc3c039bbe957b11d.jpg?s=a75Kl3NLu04J', 169.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (6, 'Pantaloni crop cu croiala dreapta Boreal', 'Mango', E'Caracteristici\nCuloare: albastru prafuit\nStil: office\nMaterial: poliester\nImprimeu: uni\nCroiala: drepti\nLungime: crop\nTalie: medie\nBuzunare: laterale\nSistem inchidere: fermoar, bucla metalica, nasture\n\nCompozitie\nExterior: 64% poliester, 34% viscoza, 2% elastan\nCaptuseala: 100% poliester\nDetalii material: garnituri tubulare: 55% poliester, 45% viscoza\n', 'https://fdcdn.akamaized.net/m/780x1132/products/32391/32390170/images/res_86966868cb85ca8cdce85db12266dfe3.jpg?s=gFVFJ2FcjnUR', 169.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (6, 'Pantaloni conici din amestec de bumbac', 'OVS', E'Caracteristici\nCuloare: oranj persan\nStil: casual, office\nMaterial: poliester, bumbac\nImprimeu: uni\nCroiala: conica\nLungime: crop\nTalie: inalta\n\nCompozitie\nExterior: 48% bumbac, 48% poliester, 4% elastan\n', 'https://fdcdn.akamaized.net/m/780x1132/products/34315/34314665/images/res_5439f7d82b7ab55323d07478e5c00c86.jpg?s=TtiaBhPRu3qq', 179.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (6, 'Pantaloni crop de reiat', 'Tommy Jeans', E'Caracteristici\nCuloare: negru\nStil: casual\nMaterial: reiat, bumbac organic\nImprimeu: uni\nCroiala: conica\nLungime: crop\nTalie: inalta\n\nCompozitie\nExterior: 98% bumbac organic, 2% elastan\n', 'https://fdcdn.akamaized.net/m/780x1132/products/34274/34273160/images/res_56aa9ba96a0f21ee52894ef8b58cc43b.jpg?s=bSbuReIG5OS6', 409.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (6, 'Pantaloni din piele ecologica cu croiala conica si talie inalta', 'DeFacto', E'Caracteristici\nCuloare: negru\nStil: casual\nMaterial: piele ecologica\nImprimeu: uni\nCroiala: conica\nLungime: crop\nTalie: inalta\nBuzunare: 2 laterale\n\nCompozitie\nExterior: 50% poliester, 35% pvc, 15% poliuretan\n', 'https://fdcdn.akamaized.net/m/780x1132/products/34223/34222914/images/res_9dda9e6d27448dfbdfc0d069850ecc86.jpg?s=u64kalXfHUG5', 129.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (6, 'Pantaloni capri de piele ecologica cu talie inalta', 'DeFacto', E'Caracteristici\nCuloare: negru\nStil: casual\nMaterial: piele ecologica\nImprimeu: uni\nCroiala: drepti\nLungime: capri\nTalie: inalta\nDetalii: talie ajustabila cu o curea\nBuzunare: 2 laterale, 2 x buzunar spate\nSistem inchidere: fermoar\n\nCompozitie\nExterior: 60% poliester, 40% poliuretan\n', 'https://fdcdn.akamaized.net/m/780x1132/products/34364/34363030/images/res_1c3c91dbbdb8c5a489a911131a4c863c.jpg?s=WPOAJ0a3Hrqp', 149.99);

-- rochii
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (7, 'Rochie midi cu prindere in talie', 'Oltre', E'Caracteristici\nCuloare: negru/maro\nStil: casual\nMaterial: poliester\nModel: clos\nImprimeu: geometric\nCroiala: pe bie\nLungime: midi\nDecolteu: rotund\nLungime maneca: maneca lunga\nDetalii: prindere in talie\n\nCompozitie\nExterior: 95% poliester, 5% elastan\n', 'https://fdcdn.akamaized.net/m/780x1132/products/33357/33356750/images/res_ebeda1405729e0bed230b7fcdbb9e7cf.jpg?s=flWCOUkI4SXS', 529.00);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (7, 'Rochie cu animal print si terminatie evazata Miss', 'Mango', E'Caracteristici\nCuloare: maro\nStil: casual\nMaterial: poliester\nModel: clos\nImprimeu: animal print\nCroiala: evazat\nLungime: mini\nDecolteu: cache-coeur\nLungime maneca: maneca lunga\nDetalii: terminatie evazata\n\nCompozitie\nExterior: 100% poliester\n', 'https://fdcdn.akamaized.net/m/780x1132/products/33921/33920635/images/res_6092688775d678df808984cb3d9f0a85.jpg?s=oZqSk5R31MkK', 199.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (7, 'Rochie vaporoasa cu model floral Fancy', 'Mango', E'Caracteristici\nCuloare: maro, albastru, bej\nStil: casual\nMaterial: poliester\nModel: clos\nImprimeu: floral\nCroiala: evazat\nLungime: midi\nDecolteu: la baza gatului, cu volane\nManeci: cu mansete cu nasturi\nLungime maneca: lunga\nDetalii: cu volane, material vaporos\n\nCompozitie\nExterior: 70% poliester, 30% poliester reciclat\nCaptuseala: 100% poliester\ng', 'https://fdcdn.akamaized.net/m/780x1132/products/33921/33920452/images/res_a6f0b909ee64593f6330da627a0df675.jpg?s=TxzhtKDsk4n5', 269.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (7, 'Rochie de satin cu barete subtiri Cortito', 'Mango', E'Caracteristici\nCuloare: negru\nStil: casual\nMaterial: poliester\nModel: drept\nImprimeu: uni\nCroiala: dreapta\nLungime: mini\nDecolteu: sal\nBarete: inguste, incrucisate pe partea din spate\nDetalii: satin\n\nCompozitie\nExterior: 100% poliester\nCaptuseala: 100% poliester\n', 'https://fdcdn.akamaized.net/m/780x1132/products/33921/33920385/images/res_d2964e5de7455c923bf0d2542d155270.jpg?s=x6keL_hVrmN3', 169.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (7, 'Rochie cu imprimeu paisley si decupaj pe partea din spate', 'Motivi', E'Caracteristici\nCuloare: negru/alb\nStil: de seara\nMaterial: poliester\nModel: clos\nImprimeu: paisley\nCroiala: evazat\nLungime: mini\nDecolteu: in v\nLungime maneca: maneca trei sferturi\nDetalii: decupaj pe partea din spate\n\nCompozitie\nExterior: 100% poliester\n', 'https://fdcdn.akamaized.net/m/780x1132/products/33216/33215950/images/res_b4d0329ecd9deefabc43f7b265dba6b0.jpg?s=_dD06gZyVyGt', 479.00);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (7, 'Rochie lejera cu maneci cazute', 'Trendyol', E'Caracteristici\nCuloare: maro camel\nStil: casual\nMaterial: bumbac, viscoza\nModel: lejer\nImprimeu: uni\nCroiala: lejer\nLungime: mini\nGuler: scurt\nManeci: cazute\nLungime maneca: maneca scurta\n\nCompozitie\nExterior: 50% viscoza, 27% bumbac, 23% poliester\n', 'https://fdcdn.akamaized.net/m/780x1132/products/34443/34442653/images/res_ca2a2cd9f7ea5846ac9fbbf4dea1c910.jpg?s=UFRjSXtjGN-F', 129.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (7, 'Rochie evazata cu cordon in talie', 'Trendyol', E'Caracteristici\nCuloare: negru\nStil: casual\nMaterial: poliester\nModel: clos\nImprimeu: uni\nCroiala: evazat\nLungime: midi\nManeci: usor transparente\nLungime maneca: lunga\nDetalii: cordon in talie, decupaj pe partea din spate\n\nCompozitie\nExterior: 100% poliester\n', 'https://fdcdn.akamaized.net/m/780x1132/products/34443/34442625/images/res_612e33467659bd9c7bf9aa58c0e49768.jpg?s=YUHMhDWJxnlB', 189.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (7, 'Rochie mini cu decolteu pe umar Asivel', 'Mango', E'Caracteristici\nCuloare: negru\nStil: elegant\nMaterial: poliester\nModel: drept\nImprimeu: uni\nCroiala: decolteu pe un umar\nLungime: mini\nDecolteu: decolteu pe un umar\nLungime maneca: maneca lunga\nDetalii: detalii cu pliuri\n\nCompozitie\nExterior: 92% poliester, 8% elastan\nCaptuseala: 100% poliester\n', 'https://fdcdn.akamaized.net/m/780x1132/products/33921/33920173/images/res_d124e888b87d78de45a03330c3672106.jpg?s=KHJ37w4rYSMO', 149.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (7, 'Rochie polo tricotata fin, din bumbac organic', 'Tommy Jeans', E'Caracteristici\nCuloare: bleumarin\nStil: casual\nMaterial: tricot\nModel: drept\nImprimeu: uni\nCroiala: cambrata\nLungime: mini\nGuler: polo\nLungime maneca: maneca scurta\nSistem inchidere: fenta scurta cu nasturi\n\nCompozitie\nExterior: 99% bumbac organic, 1% elastan\n', 'https://fdcdn.akamaized.net/m/780x1132/products/34274/34273032/images/res_b3caa298ccc86b7832321ad558b4bd74.jpg?s=WmbSA6fi-PQX', 399.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (7, 'Rochie midi cu imprimeu floral Ellie', 'Only', E'Caracteristici\nCuloare: verde feriga/lila prafuit/maro camel\nStil: casual\nMaterial: poliester\nModel: clos\nImprimeu: floral\nCroiala: evazat\nLungime: midi\nGuler: ascutit\nLungime maneca: maneca lunga\nDetalii: cordon in talie\n\nCompozitie\nExterior: 100% poliester\nInfo model\nModelul poarta un produs de marimea S.\nMarimi model: 178 cm inaltime, 83 cm bust, 59 cm talie, 90 cm sold\n', 'https://fdcdn.akamaized.net/m/780x1132/products/34280/34279321/images/res_fea9a2d51a7b6891ec209f36f669c417.jpg?s=YBd4y_KCcXpn', 289.99);

-- tricouri
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (8, 'Tricou cu decolteu la baza gatului si imprimeu cu desene', 'JdY', E'Caracteristici\nCuloare: lila prafuit\nImprimeu: desene animate\nMaterial: bumbac\nCroiala: regular fit\nStil: casual\nModel: decolteu la baza gatului\nLungime maneca: maneca scurta\n\nCompozitie\nExterior: 100% bumbac\n', 'https://fdcdn.akamaized.net/m/780x1132/products/34458/34457113/images/res_5c1e920dcd11901ac302d4995bca715e.jpg?s=vf_cQl4IDXXW', 99.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (8, 'Tricou cu decolteu la baza gatului Sea You Soon', 'Jack Wolfskin', E'Caracteristici\nCuloare: roz pal\nImprimeu: text\nMaterial: bumbac\nCroiala: regular fit\nStil: casual\nModel: decolteu la baza gatului\nLungime maneca: maneca scurta\n\nCompozitie\nExterior: 100% bumbac\n', 'https://fdcdn.akamaized.net/m/780x1132/products/34140/34139257/images/res_7032c0e2952ed56a3b9703a54884779f.jpg?s=E6z47v0wVTl-', 199.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (8, 'Tricou din amestec de bumbac organic cu maneci tip clopot', 'EDC by Esprit', E'Caracteristici\nCuloare: verde englez\nImprimeu: uni\nMaterial: bumbac organic\nCroiala: regular fit\nStil: casual\nModel: decolteu la baza gatului\nManeci: clopot\nLungime maneca: maneci medii\n\nCompozitie\nExterior: 100% bumbac organic\n', 'https://fdcdn.akamaized.net/m/780x1132/products/31087/31086678/images/res_009baf96ada3eb3bfeda6029ad75fd30.jpg?s=rQas0Ffhb1-k', 129.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (8, 'Tricou cu model in dungi si logo brodat', 'Levi''s', E'Caracteristici\nCuloare: bej\nImprimeu: dungi, logo\nMaterial: bumbac\nCroiala: regular fit\nStil: casual\nModel: decolteu la baza gatului\nLungime maneca: maneca scurta\nDetalii: broderie logo\n\nCompozitie\nExterior: 100% bumbac\n', 'https://fdcdn.akamaized.net/m/780x1132/products/34502/34501998/images/res_f227ea535db76014ca3dd3b2a0bfaf6f.jpg?s=sb9VAx6XOfQN', 179.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (8, 'Tricou cu imprimeu grafic Himalaya Flower', 'Jack Wolfksin', E'Caracteristici\nCuloare: verde persan\nImprimeu: floral, grafic\nMaterial: poliester, bumbac organic\nCroiala: regular fit\nStil: casual\nModel: decolteu la baza gatului\nLungime maneca: maneca scurta\n\nCompozitie\nExterior: 60% bumbac organic, 40% poliester\nInfo model\nModelul poarta un produs de marimea S.\nMarimi model: 178 cm inaltime, 83 cm bust, 59 cm talie, 90 cm sold\n', 'https://fdcdn.akamaized.net/m/780x1132/products/34140/34139384/images/res_57c2fa46482a3d392c42c8a8f765dc46.jpg?s=30Pk0t2QOUiP', 139.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (8, 'Tricou cu model in dungi', 'Levi''s', E'Caracteristici\nCuloare: gri inchis/alb\nImprimeu: dungi\nMaterial: bumbac\nCroiala: regular fit\nStil: casual\nModel: decolteu la baza gatului\nDecolteu: rotund\nLungime maneca: maneca scurta\n\nCompozitie\nExterior: 100% bumbac\n', 'https://fdcdn.akamaized.net/m/780x1132/products/34502/34501966/images/res_fad3d7ed7b18774be9963dd11e5d48ad.jpg?s=fgTjhj7sfTTU', 149.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (8, 'Tricou crop din bumbac organic', 'Tommy Jeans', E'Caracteristici\nCuloare: alb\nImprimeu: logo\nMaterial: bumbac organic\nCroiala: regular fit\nStil: casual\nModel: decolteu la baza gatului\nLungime maneca: maneca scurta\nDetalii: lungime crop\n\nCompozitie\nExterior: 100% bumbac organic\n', 'https://fdcdn.akamaized.net/m/780x1132/products/34274/34273054/images/res_4a74b629faa91fd3026c84af635b5e90.jpg?s=LY8L7oMjlZD3', 259.00);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (8, 'Tricou cu logo cu strasuri', 'Pepe Jeans London', E'Caracteristici\nCuloare: gri inchis melange/albastru\nImprimeu: logo\nMaterial: poliester, bumbac\nCroiala: regular fit\nStil: casual\nModel: decolteu la baza gatului\nLungime maneca: maneca scurta\nDetalii: aplicatii din strasuri\n\nCompozitie\nExterior: 50% poliester, 38% bumbac, 12% viscoza\n', 'https://fdcdn.akamaized.net/m/780x1132/products/33774/33773694/images/res_5aeb8b6e62c1942f48df2e8cd9c582e6.jpg?s=Mgn-f2Xu7Q6O', 199.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (8, 'Tricou cu decolteu la baza gatului si ciucuri din plasa', 'Love Moschino', E'Caracteristici\nCuloare: negru/maro/roz\nImprimeu: grafic\nMaterial: bumbac, elastan\nCroiala: regular fit\nStil: casual\nModel: decolteu la baza gatului\nLungime maneca: maneca scurta\nDetalii: aplicatii cu ciucuri\n\nCompozitie\nExterior: 93% bumbac,7% elastan\nDetalii material: 98% bumbac, 2% elastan\nInfo model\nModelul poarta un produs de marimea S/40 IT.\nMarimi model: 180 cm inaltime, 86 cm bust, 65 cm talie, 94 cm sold\n', 'https://fdcdn.akamaized.net/m/780x1132/products/34314/34313969/images/res_74ba3cd328b685f440fe52bbcf64c99d.jpg?s=VLJ0EAQ6ee6k', 539.99);
INSERT INTO PRODUCTS(category_id, name, brand, description, image, price) VALUES (8, 'Tricou de bumbac cu imprimeu origami', 'Armani Exchange', E'Caracteristici\nCuloare: negru/alb\nImprimeu: grafic\nMaterial: bumbac\nCroiala: regular fit\nStil: casual\nModel: decolteu la baza gatului\nLungime maneca: maneca scurta\n\nCompozitie\nExterior: 100% bumbac\nInfo model\nModelul poarta un produs de marimea S.\nMarimi model: 178 cm inaltime, 80 cm bust, 63 cm talie, 91 cm sold\n', 'https://fdcdn.akamaized.net/m/780x1132/products/34265/34264336/images/res_ab8e0836c908c97330184e20976ca27f.jpg?s=b6lqKFBu5wpy', 289.99);

-- trigger pentru update automat de stoc
CREATE OR REPLACE FUNCTION update_stock()
    RETURNS TRIGGER
    LANGUAGE PLPGSQL
AS
$$
BEGIN
    IF NEW.size = 'XS' THEN
        UPDATE STOCK
        SET XS = XS - NEW.pieces
        WHERE product_id = NEW.product_id;
    ELSIF NEW.size = 'S' THEN
        UPDATE STOCK
        SET S = S - NEW.pieces
        WHERE product_id = NEW.product_id;
    ELSIF NEW.size = 'M' THEN
        UPDATE STOCK
        SET M = M - NEW.pieces
        WHERE product_id = NEW.product_id;
    ELSIF NEW.size = 'L' THEN
        UPDATE STOCK
        SET L = L - NEW.pieces
        WHERE product_id = NEW.product_id;
    ELSE
        UPDATE STOCK
        SET XL = XL - NEW.pieces
        WHERE product_id = NEW.product_id;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER update_stock_trigger
    AFTER UPDATE OF order_id
    ON CART
    FOR EACH ROW
EXECUTE PROCEDURE update_stock();